### ISSUE TITLE
Missing Public API to Create AbsolutePath from Raw Path

### ISSUE THREAD

**Issue by Sewer56** [Nexus-Mods/NexusMods.Paths#3]
# Improvement

At some point in time, we made the APIs and extension that allow for instantiating `AbsolutePath` directly as `internal` or `private`; mostly as a safety precaution as end users of the library are expected to use paths returned by the library rather than adding their own.

## Currently 

The predecessors of the highlighted APIs here https://github.com/Nexus-Mods/NexusMods.Paths/blob/18ff0f1e8d76324d87360cbdd84ec2aa7930dea0/src/NexusMods.Paths/AbsolutePath.cs#L77-L112 used to be public, but have been privatized at some point in development as the consumer (App) did not use them.

## We want

Some sort of `Unsafe` public API for creating `AbsolutePath`(s) from raw paths. 
Either by exposing currently internal APIs, or adding alternatives; it's up for discussion.

## Workaround

The current workaround is to define a `ConfigurationPath` and grab an absolute path from there.

```csharp
new ConfigurationPath(state.DownloadPath, FileSystem.Shared).ToAbsolutePath();
```

This is what the App does to get arbitrary `AbsolutePath`(s) when instantiating items that require them; not as a workaround but simply because we use these paths in configs.

## Note

I could just throw a PR making some of the highlighted methods above private; but I've opened this as an issue to see if anyone has particular opinions.

**Comment by erri120** [comment]
The current API forces "input paths" to be sanitized and converted into our internal format. We don't expose an _unsafe_ API because, as the name implies, it would be unsafe and can cause issues that are hard to debug. There is no benefit to having such an API, as it will only introduce headaches when used incorrectly. Furthermore, since such an API wouldn't be used in hot paths, the performance benefits of not doing sanitizations aren't worth it.

The API is locked down on purpose to force consumers to do the right thing.

**Comment by Al12rs** [comment]
What about `FromUnsanitizedPath` that does the sanitization? I'm not quite clear what the process should be to obtain a sanitized AbsolutePath from an unsanitized string

**Comment by erri120** [comment]
Creation of an `AbsolutePath` is done via the `IFileSystem` API:

https://github.com/Nexus-Mods/NexusMods.Paths/blob/18ff0f1e8d76324d87360cbdd84ec2aa7930dea0/src/NexusMods.Paths/FileSystemAbstraction/IFileSystem.cs#L60-L73

**Comment by Al12rs** [comment]
I see, I didn't know about that. RelativePath seems to work differently which confused me.

**Comment by Sewer56** [comment]
> Creation of an `AbsolutePath` is done via the `IFileSystem` API:
> 
> https://github.com/Nexus-Mods/NexusMods.Paths/blob/18ff0f1e8d76324d87360cbdd84ec2aa7930dea0/src/NexusMods.Paths/FileSystemAbstraction/IFileSystem.cs#L60-L73

Oh, this already has what's needed.

Welp, I feel pretty stupid now. I don't really know how I missed it, I even cloned the project to look around, well... this is awkward...

#closed
